### ISSUE TITLE
sklearn joblib is deprecated

### ISSUE THREAD

**Issue by quintinvh** [UDST/zone_model#30]
As of `sklearn` version 0.23, the `sklearn.externals.joblib` import is deprecated. Instead, one should install `joblib` directly (e.g. `pip install joblib`) and update the import in `zone_model/utils.py`. I've tested this locally and it ran successfully.

Implications for other packages that need to be updated:
`Python` >= 3.6 (currently 3.4 in this repo)
`NumPy` >= 1.13.3 (currently 1.1.0 in this repo)

Is it possible to update `utils.py` to support this version of `sklearn` or should I make the changes (and work) on a separate branch?

**Comment by smmaurer** [comment]
Hi @quintinvh, thanks for reporting this, and for figuring out a fix! 

I'm testing it out and don't anticipate any issues. We can update the `import` statement so that it uses either `joblib` or `sklearn` depending on which is available.

**Comment by quintinvh** [comment]
Sounds good, thanks @smmaurer !

**Comment by smmaurer** [comment]
Ok, this has been fixed in PR #31 and merged into the `master` branch.
